name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # हर 5 मिनट में सिंक करेगा
  workflow_dispatch: # मैनुअली रन करने का विकल्प

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync with Upstream using GH CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo sync Premium-png/BDIX-IPTV -b main
